### ISSUE TITLE
Exception: Invalid Wallet

### ISSUE THREAD

**Issue by lukassgramm** [fxwalletOfficial/flutter_web3_webview#1]
Console Error:
```bash
[AndroidInAppWebViewController] (android) WebView ID 0 calling "onConsoleMessage" using {messageLevel: 0, message: %csmart-router:log %c[BEST_AMM](useBestAMMTradeFromQuoterWorker) chain 56, 0.5 USDT -> BNB, tradeType 0%c +884ms color: #33CCFF color: inherit color: #33CCFF [object Object]}
E/JSBridgeInterface( 8656): error, Exception: Invalid wallet
[AndroidInAppWebViewController] (android) WebView ID 0 calling "onConsoleMessage" using {messageLevel: 1, message: request payload [object Object] false}
[AndroidInAppWebViewController] (android) WebView ID 0 calling "FxWalletHandler" using [{method: eth_gasPrice}]
[JavaScript Handler "FxWalletHandler"] Exception: Invalid wallet
#0      Web3WebviewState._onDefaultCallback (package:flutter_web3_webview/src/webview.dart:512:43)
#1      Web3WebviewState._onHandleCallback (package:flutter_web3_webview/src/webview.dart:426:16)
#2      Web3WebviewState._onWebViewCreated.<anonymous closure> (package:flutter_web3_webview/src/webview.dart:382:29)
#3      AndroidInAppWebViewController._handleMethod (package:flutter_inappwebview_android/src/in_app_webview/in_app_webview_controller.dart:1542:73)
#4      InternalChannelController.initMethodCallHandler.<anonymous closure> (package:flutter_inappwebview_platform_interface/src/util.dart:631:30)
#5      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:571:55)
#6      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:564:34)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:618:35)
```

I tried to do the Swap of 0.5 USDT network BSC on Pancake Swap. Wallet connection is OK

Dart Code: 

```dart


class Page extends StatefulWidget {
  const Page({super.key});

  @override
  PageState createState() => PageState();
}

class PageState extends State<Page> {
  String _title = '';
  int _chainId = 56; //BSC

  String ethAddress = '0x04...';
  String ethPrivateKey = '89...'; //I tried both with 0x and without at first

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text(_title)),
        body: Web3Webview(
            isWeb3: true,
            initialUrlRequest: URLRequest(url: WebUri('https://pancakeswap.finance/')),
            settings: Web3Settings(
                eth: Web3EthSettings(
              chainId: _chainId,
            )),
            shouldOverrideUrlLoading: (p0, action) async => NavigationActionPolicy.ALLOW,
            onTitleChanged: _onTitleChanged,
            ethAccounts: _ethAccounts,
            ethChainId: _ethChainId,
            walletSwitchEthereumChain: _walletSwitchEthereumChain));
  }

  void _onTitleChanged(InAppWebViewController c, String? value) {
    if (value == null || value == _title) return;

    _title = value;
    setState(() {});
  }

  Future<int> _ethChainId() async {
    return _chainId;
  }

  Future<List<String>> _ethAccounts() async {
    return [ethAddress];
  }

  Future<bool> _walletSwitchEthereumChain(JsAddEthereumChain data) async {
    _chainId = int.parse((data.chainId)?.replaceFirst('0x', '') ?? '1', radix: 16);
    return true;
  }
}
```

**Comment by peipeitu** [comment]
Hello.

**Comment by peipeitu** [comment]
Error `Invalid Wallet` is shown when required method params is not initial. 
And on your issue, it is because you didn't init method named `onDefaultCallback`. It will be called when method is not declared advance. Most are conventional RPC requests that do not need a private key.

On your console, it is a `eth_gasPrice` rpc method has been called.
